version: '3.8'

services:
  postgres-db: 
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: paymentdb
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data  
volumes:
  postgres_data: